CREATE TYPE "media_type" AS ENUM (
  'image',
  'video',
  'image_360'
);

CREATE TYPE "request_status" AS ENUM (
  'pending_review',
  'pending_appraisal',
  'appraising',
  'price_quoted',
  'seller_accepted',
  'seller_rejected',
  'listed',
  'sold',
  'completed',
  'rejected_by_admin',
  'returned'
);

CREATE TYPE "physical_status" AS ENUM (
  'not_received',
  'in_appraisal',
  'in_stock',
  'shipping_to_buyer',
  'returning_to_seller'
);

CREATE TYPE "product_status" AS ENUM (
  'for_sale',
  'sold'
);

CREATE TYPE "order_status" AS ENUM (
  'pending_payment',
  'confirmed',
  'shipping',
  'delivered',
  'cancelled',
  'failed'
);

CREATE TYPE "user_status" AS ENUM (
  'pending_activation',
  'active',
  'suspended'
);

CREATE TABLE "Users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "phone_number" varchar(20) UNIQUE,
  "status" user_status NOT NULL DEFAULT 'pending_activation',
  "activation_token" varchar(255) UNIQUE,
  "reset_password_token" varchar(255) UNIQUE,
  "reset_password_expires" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "Roles" (
  "role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "User_Roles" (
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "UserAddresses" (
  "address_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "full_name" varchar(255) NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "address_line1" text NOT NULL,
  "address_line2" text,
  "city" varchar(100) NOT NULL,
  "district" varchar(100) NOT NULL,
  "ward" varchar(100) NOT NULL,
  "is_default" boolean DEFAULT false
);

CREATE TABLE "AppraisalRequests" (
  "request_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" integer NOT NULL,
  "brand" varchar(100) NOT NULL,
  "product_name" varchar(255) NOT NULL,
  "condition" text NOT NULL,
  "condition_details" text,
  "accessories" text,
  "status" request_status NOT NULL DEFAULT 'pending_review',
  "physical_status" physical_status NOT NULL DEFAULT 'not_received',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "ProductMedia" (
  "media_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer NOT NULL,
  "media_type" media_type NOT NULL DEFAULT 'image',
  "media_url" varchar(255) NOT NULL,
  "display_order" integer DEFAULT 0,
  "uploaded_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "AppraisalReports" (
  "report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer UNIQUE NOT NULL,
  "appraiser_id" integer NOT NULL,
  "authenticity_result" varchar(100) NOT NULL,
  "detailed_assessment" text NOT NULL,
  "purchase_price" decimal(12,2) NOT NULL,
  "listing_price" decimal(12,2) NOT NULL,
  "serial_number" varchar(100),
  "movement_type" varchar(100),
  "case_material" varchar(100),
  "strap_material" varchar(100),
  "dimensions" varchar(100),
  "report_pdf_url" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Products" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer UNIQUE NOT NULL,
  "report_id" integer UNIQUE NOT NULL,
  "sku" varchar(100) UNIQUE NOT NULL,
  "brand" varchar(100) NOT NULL,
  "product_name" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "listing_price" decimal(12,2) NOT NULL,
  "status" product_status NOT NULL DEFAULT 'for_sale',
  "movement_type" varchar(100),
  "case_material" varchar(100),
  "strap_material" varchar(100),
  "listed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_code" varchar(50) UNIQUE NOT NULL,
  "buyer_id" integer NOT NULL,
  "product_id" integer UNIQUE NOT NULL,
  "subtotal" decimal(12,2) NOT NULL,
  "shipping_fee" decimal(10,2) DEFAULT 0,
  "discount_amount" decimal(12,2) DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL,
  "shipping_address" text NOT NULL,
  "shipping_method" varchar(100),
  "tracking_code" varchar(100),
  "payment_method" varchar(50) NOT NULL,
  "status" order_status NOT NULL DEFAULT 'pending_payment',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "Transactions" (
  "transaction_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "gateway_transaction_id" varchar(255),
  "payment_gateway" varchar(50) NOT NULL,
  "amount" decimal(12,2) NOT NULL,
  "status" varchar(50) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Payouts" (
  "payout_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer UNIQUE NOT NULL,
  "request_id" integer UNIQUE NOT NULL,
  "seller_id" integer NOT NULL,
  "payout_amount" decimal(12,2) NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "paid_at" timestamp
);

CREATE TABLE "Notifications" (
  "notification_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" text NOT NULL,
  "link_url" varchar(255),
  "is_read" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "StaticPages" (
  "page_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" varchar(100) UNIQUE NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" text,
  "updated_at" timestamp
);

CREATE TABLE "ContactMessages" (
  "message_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(255),
  "email" varchar(255) NOT NULL,
  "phone_number" varchar(20),
  "message" text NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'new',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

COMMENT ON COLUMN "Roles"."role_name" IS 'e.g., NguoiMua, NguoiBan, NguoiThamDinh, Admin';

COMMENT ON COLUMN "UserAddresses"."full_name" IS 'Tên người nhận (cho checkout FN-309)';

COMMENT ON COLUMN "UserAddresses"."phone_number" IS 'SĐT người nhận (cho checkout FN-309)';

COMMENT ON COLUMN "UserAddresses"."address_line1" IS 'Địa chỉ (cho checkout FN-309)';

COMMENT ON COLUMN "AppraisalRequests"."condition" IS 'Tình trạng (FN-101)';

COMMENT ON COLUMN "AppraisalRequests"."condition_details" IS 'Mô tả chi tiết (FN-101)';

COMMENT ON COLUMN "AppraisalRequests"."accessories" IS 'Phụ kiện/Giấy tờ đi kèm (FN-101)';

COMMENT ON TABLE "ProductMedia" IS 'Lưu trữ hình ảnh cho FN-102';

COMMENT ON COLUMN "AppraisalReports"."authenticity_result" IS 'Thật / Giả';

COMMENT ON COLUMN "AppraisalReports"."detailed_assessment" IS 'Đánh giá tình trạng chi tiết (vỏ, máy...)';

COMMENT ON COLUMN "AppraisalReports"."purchase_price" IS 'Giá Mua Lại đề xuất';

COMMENT ON COLUMN "AppraisalReports"."listing_price" IS 'Giá Niêm Yết đề xuất';

COMMENT ON COLUMN "Products"."description" IS 'Mô tả công khai, lấy từ detailed_assessment (FN-305)';

COMMENT ON COLUMN "Orders"."order_code" IS 'Mã đơn hàng thân thiện, vd: WX-12345';

COMMENT ON COLUMN "Orders"."product_id" IS 'Mỗi đơn hàng chỉ có 1 sản phẩm duy nhất';

COMMENT ON COLUMN "Orders"."subtotal" IS 'Giá gốc sản phẩm';

COMMENT ON COLUMN "Orders"."total_amount" IS 'Số tiền cuối cùng cần thanh toán';

COMMENT ON COLUMN "Orders"."shipping_address" IS 'Snapshot địa chỉ tại thời điểm đặt hàng';

COMMENT ON TABLE "Transactions" IS 'Hỗ trợ FN-404 (Xác nhận chuyển khoản thủ công)';

COMMENT ON COLUMN "Transactions"."gateway_transaction_id" IS 'Mã giao dịch từ VNPAY, Momo...';

COMMENT ON COLUMN "Transactions"."payment_gateway" IS 'VNPAY, Bank Transfer... (FN-311)';

COMMENT ON COLUMN "Transactions"."status" IS 'success, pending, failed';

COMMENT ON TABLE "Payouts" IS 'Quản lý đối soát và chi trả cho Người Bán.';

COMMENT ON COLUMN "Payouts"."order_id" IS 'Kích hoạt bởi đơn hàng FN-408';

COMMENT ON COLUMN "Payouts"."seller_id" IS 'Người bán nhận tiền (FN-412)';

COMMENT ON COLUMN "Payouts"."payout_amount" IS 'Số tiền chi trả = Giá Mua Lại (FN-412)';

COMMENT ON COLUMN "Payouts"."status" IS 'pending, completed';

COMMENT ON COLUMN "Payouts"."paid_at" IS 'Cập nhật khi nhấn FN-413';

COMMENT ON TABLE "Notifications" IS 'Dùng cho các thông báo (FN-203, FN-208, FN-315...)';

COMMENT ON COLUMN "Notifications"."user_id" IS 'Người nhận thông báo';

COMMENT ON COLUMN "Notifications"."link_url" IS 'Đường dẫn khi click vào thông báo (vd: /dashboard/requests/123)';

COMMENT ON TABLE "StaticPages" IS 'Lưu nội dung các trang tĩnh.';

COMMENT ON COLUMN "StaticPages"."slug" IS 'e.g., ve-chung-toi, dieu-khoan-dich-vu';

COMMENT ON TABLE "ContactMessages" IS 'Lưu trữ tin nhắn từ form liên hệ.';

COMMENT ON COLUMN "ContactMessages"."status" IS 'new, read, archived';

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("role_id");

ALTER TABLE "UserAddresses" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "AppraisalRequests" ADD FOREIGN KEY ("seller_id") REFERENCES "Users" ("user_id");

ALTER TABLE "ProductMedia" ADD FOREIGN KEY ("request_id") REFERENCES "AppraisalRequests" ("request_id");

ALTER TABLE "AppraisalReports" ADD FOREIGN KEY ("request_id") REFERENCES "AppraisalRequests" ("request_id");

ALTER TABLE "AppraisalReports" ADD FOREIGN KEY ("appraiser_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Products" ADD FOREIGN KEY ("request_id") REFERENCES "AppraisalRequests" ("request_id");

ALTER TABLE "Products" ADD FOREIGN KEY ("report_id") REFERENCES "AppraisalReports" ("report_id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("buyer_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("product_id") REFERENCES "Products" ("product_id");

ALTER TABLE "Transactions" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id");

ALTER TABLE "Payouts" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id");

ALTER TABLE "Payouts" ADD FOREIGN KEY ("request_id") REFERENCES "AppraisalRequests" ("request_id");

ALTER TABLE "Payouts" ADD FOREIGN KEY ("seller_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");
